require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - curlybars.gemspec

#
# Special cases
#

Lint/EmptyWhen:
  Exclude:
    - lib/curlybars/node/path.rb

Performance/FixedSize:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/curlybars/template_handler_spec.rb'
    - 'spec/integration/cache_spec.rb'

RSpec/NestedGroups:
  Exclude:
    - spec/**/*

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/curlybars/rendering_support_spec.rb'
    - 'spec/integration/node/each_else_spec.rb'

Security/Eval:
  Exclude:
    - spec/integration/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - spec/dummy/**/*

Style/RegexpLiteral:
  Exclude:
    - lib/curlybars/lexer.rb

Style/Semicolon:
  Exclude:
    - lib/curlybars/lexer.rb

Style/SymbolProc:
  Exclude:
    - spec/spec_helper.rb

#
# Configured cops
#

# Align the elements of a hash literal if they span more than one line.
Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

# Align the parameters of a method call if they span more than one line.
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Indentation of when in a case/when/[else/]end.
Layout/CaseIndentation:
  EnforcedStyle: end

# Checks the indentation of the first parameter in a method call.
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

# Checks the indentation of the first key in a hash literal.
Layout/IndentHash:
  EnforcedStyle: consistent

# Checks indentation of binary operations that span more than one line.
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Align ends correctly.
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Checks for consistent style of stub's return setting.
RSpec/ReturnFromStub:
  EnforcedStyle: block

# Use alias instead of alias_method.
Style/Alias:
  EnforcedStyle: prefer_alias_method

# Checks the formatting of empty method definitions.
Style/EmptyMethod:
  EnforcedStyle: expanded

# Enforce the use of Kernel#sprintf, Kernel#format or String#%.
Style/FormatString:
  EnforcedStyle: percent

#
# Disabled cops
#

Layout/AlignArray:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WordArray:
  Enabled: false
