gem "bundler"
gem "byebug"
gem "rake"
gem "rspec-rails"
gem "rubocop", "~> 1.57"
gem "rubocop-performance", "~> 1.19"
gem "rubocop-rake", "~> 0.6"
gem "rubocop-rspec", "~> 3"
gem "rubocop-rspec_rails"
