require 'integration/presenters/baz_presenter'
require 'integration/presenters/blog_presenter'
require 'integration/presenters/item_presenter'
require 'integration/presenters/item_show_presenter'
require 'integration/presenters/letter_presenter'
